# Generated by Django 4.0.3 on 2022-03-11 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_type', models.CharField(max_length=50)),
                ('file_path', models.FilePathField()),
                ('original_YN', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_class', models.CharField(max_length=50)),
                ('obj_name', models.CharField(max_length=200)),
                ('LB_x', models.FloatField()),
                ('LB_y', models.FloatField()),
                ('RT_x', models.FloatField()),
                ('RT_y', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_info.document')),
            ],
        ),
    ]
