# Generated by Django 4.0.3 on 2022-03-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='obj_name',
            new_name='obj_content',
        ),
    ]
