# Generated by Django 4.0.3 on 2022-03-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0003_alter_object_obj_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
    ]
