# Generated by Django 4.0.3 on 2022-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0004_alter_document_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='LB_x',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='LB_y',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='RT_x',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='RT_y',
            field=models.FloatField(blank=True),
        ),
    ]
