# Generated by Django 4.0.3 on 2022-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0005_alter_object_lb_x_alter_object_lb_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='LB_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='LB_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='RT_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='RT_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
