# Generated by Django 4.0.3 on 2022-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0006_alter_object_lb_x_alter_object_lb_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='obj_content',
            field=models.TextField(null=True),
        ),
    ]
