# Generated by Django 4.0.3 on 2022-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0009_alter_object_obj_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='obj_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_content',
            field=models.TextField(),
        ),
    ]
