# Generated by Django 4.0.3 on 2022-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0011_alter_object_obj_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploadTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to='Upload Files/'),
        ),
    ]
