# Generated by Django 4.0.3 on 2022-03-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0012_document_uploadtime_alter_document_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploadTime',
        ),
    ]
