# Generated by Django 4.0.3 on 2022-03-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_info', '0014_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
